server:
  port: 80
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/163music?autoReconnect=true&useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
    database: mysql
    hibernate:
      ddl-auto: update
  jooq:
    sql-dialect: org.hibernate.dialect.MySQL5Dialect
